### ISSUE TITLE
Create Error Message for Test > MaxNumberOfTestsForEachTestSuite 

### ISSUE THREAD

**Issue by Beidendorfer** [tcunit/TcUnit#128]
If there are more tests in a TestSuit than are set in the  parameter list MaxNumberOfTestsForEachTestSuite (100)
All tests above this limit will be marked as failed, but no error log will be issued.

 It would be nice to have a log entry here that says "There are more tests than MaxNumberOfTestsForEachTestSuite, please change the value".

Example: No exact information why the tests failed 
(Reason: More Test(216) in a TestSuit than parameterized in MaxNumberOfTestsForEachTestSuite (100))

![image](https://user-images.githubusercontent.com/40072981/102712284-3842fb80-42c0-11eb-8037-ef9d0c6e858c.png)

**Comment by sagatowski** [comment]
Good suggestion!

**Comment by Beidendorfer** [comment]
I added a solution in my PR #131

![image](https://user-images.githubusercontent.com/40072981/103444926-2113ee80-4c6e-11eb-8de9-a54cfeceb5a3.png)

**Comment by sagatowski** [comment]
Solved in 26f40b4.
