### ISSUE TITLE
https://tcunit.org inaccessible due to SSL incompatiblity

### ISSUE THREAD

**Issue by RodneyRichardson** [tcunit/TcUnit#136]
Attempting to access https://tcunit.org from Windows browsers (Edge 88 , Chrome 87, Firefox 84) results in a connection error saying the browser and server do not share an common protocol and cipher (ERR_SSL_VERSION_OR_CIPHER_MISMATCH (Chrome, Edge), or SSL_ERROR_NO_CYPHER_OVERLAP (Firefox)).

**Comment by sagatowski** [comment]
Hi @RodneyRichardson! Thanks for giving a heads-up!
There was a problem with the hosting. Now it works fine.
