### ISSUE TITLE
TcUnit-Verifier: Duplicate log4net package in packages.config

### ISSUE THREAD

**Issue by RodneyRichardson** [tcunit/TcUnit#143]
https://github.com/tcunit/TcUnit/blob/master/TcUnit-Verifier/TcUnit-Verifier_DotNet/TcUnit-Verifier/packages.config

This contains two entries for log4net, causing an error when trying to restore packages.

Please delete one entry.

**Comment by sagatowski** [comment]
Thanks for pointing this one out @RodneyRichardson! I'll fix it.

**Comment by sagatowski** [comment]
Solved with commit fb1bc41.
