### ISSUE TITLE
Visual studio path

### ISSUE THREAD

**Issue by kumaraswamygaviyappa** [tcunit/TcUnit#154]
Hallo,

The VS path was found as marked in RED line but latter Error as Marked in Orange.
Any clues please.

![image](https://user-images.githubusercontent.com/10028131/121853248-fcc63e80-ccf0-11eb-89fc-ae60258b34b1.png)

**Comment by sagatowski** [comment]
`LaunchPlcStaticAnalysis.bat?` This does not seem to be related to TcUnit?

**Comment by kumaraswamygaviyappa** [comment]
Hi @sagatowski ,

Yes, But any help is much appreciated as i am struggling from this from few days.
`LaunchPlcStaticAnalysis.bat` works fine when executed from CMD.
Error occurs only while using Jenkins.

**Comment by sagatowski** [comment]
Then my guess is that this is a privilegesproblem. Have you made sure that the Jenkins agent has the same privileges as the user running from the CMD?

**Comment by kumaraswamygaviyappa** [comment]
I couldn't find the privileges , i could solve it by changing `JENKINS_HOME`. 
Could give me some pointers  to find the privileges in Jenkins.

**Comment by sagatowski** [comment]
Jenkins_HOME? How did that change the problem? So what was the problem then?

I guess we can close this issue then?

**Comment by kumaraswamygaviyappa** [comment]
Followed This Link [JENKINS_HOME](https://stackoverflow.com/questions/34854377/how-to-change-workspace-and-build-record-root-directory-on-jenkins)

**Comment by sagatowski** [comment]
Thanks @kumaraswamygaviyappa !

I have also written a little about this:
https://alltwincat.com/2018/07/26/ci-cd-with-twincat-part-two/

And more importantly:
https://alltwincat.com/2018/10/04/ci-cd-with-twincat-part-four/

(search for the word "weekend" in the second link and you will find what I mean)
