### ISSUE TITLE
Missing test results

### ISSUE THREAD

**Issue by bernienor** [tcunit/TcUnit#160]
The summary of test results disappeared from my project. Failing tests would still show up. After some investigation I think I found the cause.

If the TEST macro called with a text string ending in a space, the test result summary for the project will fail to print.

This fails:
TEST('Home command parsing test ');

This works as it should:
TEST('Home command parsing test');

Using TcUnit 1.2.0.0

**Comment by bernienor** [comment]
Another observation:

When it fails, the tests are run continuously. I guess the missing summery is a result of the tests never finish.

**Comment by sagatowski** [comment]
Thanks for this report. I can confirm that I get the same result.
This will have to be investigated.

**Comment by sagatowski** [comment]
@bernienor I'm onto a solution. I'll let you know when it's done.

**Comment by sagatowski** [comment]
Issue solved (see commit 5059342). @bernienor  You can create TcUnit from source if you want this feature, I'll wait with a release until I've fixed some other issues.

**Comment by bernienor** [comment]
Thanks!

As long as I know how to fix this in my code I'm happy. 

Cheers
Bernie

**Comment by sagatowski** [comment]
Great, appreciate that you found this bug! Thanks.
