### ISSUE TITLE
Page fault when TotalAsserts equals 0 in FB_AssertResultStatic.AddAssertResult

### ISSUE THREAD

**Issue by supermedde** [tcunit/TcUnit#167]
![pagefault](https://user-images.githubusercontent.com/93373292/139399381-5c7fa209-f9b8-4cd5-b6cb-226597cd439e.jpg)

**Comment by sagatowski** [comment]
I'll close this issue. From what I can see, all that needs to be done is to call TcUnit.RUN(). If you find there is still a bug in TcUnit, please re-open it.
