### ISSUE TITLE
The method "AssertEquals_WORD" of FB_TestSuite sets the wrong type "Type_UINT"

### ISSUE THREAD

**Issue by JoergWitt** [tcunit/TcUnit#184]
**Describe the bug**
The AssertEquals_WORD writes type Type_UINT into the AssertionType field of the "Tests" array. The reason for that is the use of the wrong parameter E_AssertionType.Type_UINT by caling the method "SetTestFailed() in line 19.

**Additional context**

![AssertEquals_WORD](https://user-images.githubusercontent.com/100140154/169840445-f068e382-b8bd-4fe5-8e6a-e27a7bb03600.PNG)

**Comment by JoergWitt** [comment]
@sagatowski  Yes, I will create a pull request.

**Comment by sagatowski** [comment]
Solved in [47e3198](https://github.com/tcunit/TcUnit/commit/47e31989df6d183a17f8bd5cfeed1e26bf366a3d)
