### ISSUE TITLE
Variable "NumberOfTestsToAnalyse" is limited to the wrong boundaries

### ISSUE THREAD

**Issue by JoergWitt** [tcunit/TcUnit#187]
**Describe the bug**
It is not possible to set the GVL variable `MaxNumberOfTestSuites` less than `MaxNumberOfTestsForEachTestSuite`. It causes compiler errors in `FB_TestResults` and `FB_TestSuite`.

The reason is the variable `NumberOfTestsToAnalyse` used in TcUnit. It is limited to:
`NumberOfTestsToAnalyse : UINT(1..GVL_Param_TcUnit.MaxNumberOfTestSuites);`

The solution is as follows, if you agree my **Expected behavior**:
`NumberOfTestsToAnalyse : UINT(1..GVL_Param_TcUnit.MaxNumberOfTestsForEachTestSuite);`

**Expected behavior**
I think, that number of test suites and number of test in each test suite are independent from each other and so I can set them independently.

**Screenshots**
![NumbreOfTestsToAnalyse](https://user-images.githubusercontent.com/100140154/172340562-77ae76e6-122c-47f6-9943-d048ac3982fa.PNG)

**Comment by JoergWitt** [comment]
Sure, will create the pull request.

**Comment by sagatowski** [comment]
Issue solved. Thanks @JoergWitt.
