### ISSUE TITLE
RUN_IN_SEQUENCE doesn't work for multiple TestSuites in 1.2.1.0 (current master)

### ISSUE THREAD

**Issue by doerk77** [tcunit/TcUnit#189]
**Describe the bug**
RUN_IN_SEQUENCE executes the tests on the first TestSuite, but the tests for the 2nd TestSuite are not being executed. 

When RUN_IN_SEQUENCE calls AreAllTestsFinished(), it returns true (because no test has been registered yet) and therefore the tests never get executed.
But the tests can only be registered in TEST_ORDERED during execution of the test suite. 

Note: It all works fine if the test suites are being executed in parallel.

**Screenshots**
Using TcUnit.RUN() and TEST()
![image](https://user-images.githubusercontent.com/82865479/173577037-a689d2c4-b553-481c-b719-cdb269c6e6a4.png)

Using TcUnit.RUN_IN_SEQUENCE() and TEST_ORDERED()
![image](https://user-images.githubusercontent.com/82865479/173577422-e3f7c7fd-b7d9-42d6-8fe6-15ebaa7e52e9.png)

![image](https://user-images.githubusercontent.com/82865479/173577491-33eb5d12-36c1-4409-ab05-3d4d465edb68.png)

![image](https://user-images.githubusercontent.com/82865479/173577531-0bb6dc52-9bc9-4150-8b9f-0b345f04e10f.png)

**Software versions**
v1.2.1.0

**Comment by sagatowski** [comment]
Your output window looks weird, you get double outputs for some reason.

1. Did you define the tests and test-suites correctly?
You have example projects for this use case here:
https://github.com/tcunit/ExampleProjects/tree/master/RunTestsInSequenceExampleProjects

Please also check this FAQ: https://tcunit.org/frequently-asked-questions/?Display_FAQ=970

2. Do you have an example project that re-creates this issue?

Note that version 1.2.1.0 of TcUnit doesn't exist. The [latest release ](https://github.com/tcunit/TcUnit/releases)is 1.2.0.0.

**Comment by doerk77** [comment]
Just tested with your sample project

![image](https://user-images.githubusercontent.com/82865479/173618585-29f9f318-ba00-4923-9c01-c13aa74a1cee.png)

As you can see there are clearly more than 4 tests throughout the various test suites. But only 4 tests get executed.

XML output states the same.
![image](https://user-images.githubusercontent.com/82865479/173619139-5a8d9682-0906-4064-b9f4-1fc3778063ed.png)


PS: I'm using the latest (unreleased) version from GitHub which tells 1.2.1.0.

**Comment by sagatowski** [comment]
Make sure to read the [contributing](https://github.com/tcunit/TcUnit/blob/master/CONTRIBUTING.md). Thanks.

**Comment by sagatowski** [comment]
Also, if you could think of any good test to add to the [TcUnit-Verifier](https://github.com/tcunit/TcUnit/tree/master/TcUnit-Verifier) to cover this case, that would be awesome!

**Comment by doerk77** [comment]
Happened between Commits [5059342](https://github.com/tcunit/TcUnit/commit/50593425817d5fe8982174a3b25e17eff38f6121) and [c7d7021](https://github.com/tcunit/TcUnit/commit/c7d7021b0d9a513c32c7167b5705bf2452e848f7)

First guess is that this is causing the issue:
![image](https://user-images.githubusercontent.com/82865479/173628237-4bdcdb45-14bd-4259-a6ae-6f08006891da.png)

But need to check in detail.
Hadn't been clean before. Therefore the workaround incl. comment ;-)

**Comment by sagatowski** [comment]
@doerk77  seems reasonable. Good work! TcUnit always needs more contributors!
Bad of me to not discover this during code review :/

Would be really good if the TcUnit-Runner would detect this failure, so we don't end up here again.

**Comment by doerk77** [comment]
Question: Is there a reason why registering tests is only possible while the testsuite is running? 

In general I'd allow it the whole time until the testsuite actually starts running. At this point in time the list should not change any more.
That way it would even allow to register tests during FB_Init or in a method with attribute 'call_after_global_init_slot'.

Not that easy to write a test how it might be possible to detect this kind of issue though... Let me think about it.

**Comment by doerk77** [comment]
> Your output window looks weird, you get double outputs for some reason.

Seems to be an ADSLOGSTR / TwinCAT feature if you have 2 projects in a single solution.

**Comment by doerk77** [comment]
> > Your output window looks weird, you get double outputs for some reason.
> 
> Seems to be an ADSLOGSTR / TwinCAT feature if you have 2 projects in a single solution.

FYI: Just checked with Beckhoff support. Inside the IDE there's an event listener instantiated per project on the PLC. Therefore the event from ADSLOGSTR is being written to the Error List window twice.
However, as far as I can see this shouldn't cause any trouble. It's just a little annoying to see it pop up multiple times.

**Comment by sagatowski** [comment]
@doerk77  Yes, you are correct. I just remember that there already was an issue on this particular topic:
https://github.com/tcunit/TcUnit/issues/92

**Comment by sagatowski** [comment]
Solved. Thanks for finding the problem @doerk77.
