### ISSUE TITLE
AddAssertResult not checking limits of AssertResults array

### ISSUE THREAD

**Issue by doerk77** [tcunit/TcUnit#190]
**Describe the bug**
When increasing TotalAsserts in method AddAssertResult  the array limits of AssertResults are not being checked, causing PLC crash due to invalid array index.

**Expected behavior**
Prevent crash by limit checks and sending error through ADSLOGSTR.
**Remark:** Prevent overflow of event logger (error should only be raised once)!!!

**Screenshots**
![image](https://user-images.githubusercontent.com/82865479/173796847-5224802d-ac16-48e4-a9ae-b1f22fa64f2d.png)

**Software versions**
v1.2.0.0

has been mentioned earlier in #153

**Comment by sagatowski** [comment]
Pull request welcome.

**Comment by sagatowski** [comment]
Solved in #193 & in commit [4a48bdd](https://github.com/tcunit/TcUnit/commit/4a48bdd61fc06e126195ad3a7d970774aee9c834)
