### ISSUE TITLE
Integrate tests in the Test explorer

### ISSUE THREAD

**Issue by Rednas83** [tcunit/TcUnit#195]
Would be cool if the created tests could be displayed and executed in the test explorer.

**Comment by sagatowski** [comment]
Agree. Not possible though as I don't have control of the TwinCAT XAE.

**Comment by sagatowski** [comment]
@Rednas83 

Actually, it is (kind of) possible today, please check:

https://github.com/philippleidig/TcUnit-VsTestAdapter
https://github.com/philippleidig/TcUnit-VsExtension
