### ISSUE TITLE
Feature Request: Use TcUnit without extending TcUnit.Fb_TestSuite

### ISSUE THREAD

**Issue by RGrabichler** [tcunit/TcUnit#198]
![image](https://user-images.githubusercontent.com/33341896/205684980-b4bc7b7f-a281-4626-8445-1758cce06bf9.png)

I use the TcOpen Framework. 
Therefore i have the TcoContect, where my MainStation, a TcoObject runs.
The FB i want to test derives from a TcoComponent.
I created a Library for this RfidHead-Compoonent and now i want to test it.
In TcUnit i have to create a FB which extends the TcUint.Fb_TestSuite, but i cannot inherit from two different Classes.
So how can i solve this.
![image](https://user-images.githubusercontent.com/33341896/205685777-2c18f86f-4fcc-43b9-93bd-ae0737f51ee1.png)
This would be the TestSuite with the TestMethods.

Thanks for Advices

**Comment by sagatowski** [comment]
This is not a feature request. This would break the current API for TcUnit. Regarding the other question, I will transfer this to discussions.
