### ISSUE TITLE
Test registering with TEST(...) space character issue

### ISSUE THREAD

**Issue by TLSM554kn** [tcunit/TcUnit#225]
When starting / registering a test with the method TEST(...) and you use a test name with a trailing ' ' space character, the test environment never finishes.

What work: TEST('TwoPlusTwoEqualsFour');
What does not work: TEST('TwoPlusTwoEqualsFour ');  // trailing space caracter in the test name

Version is TcUnit V1.2.0.0

**Comment by sagatowski** [comment]
This issue is already resolved in the master-branch and will be included in the TcUnit 1.3.0.0 release.

**Comment by sagatowski** [comment]
Related issue #160.
