### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by whitecider** [tcunit/TcUnit#234]
the link from FAQ doesn't work. 
https://tcunit.org/temp/TimedTest_1x.zip

**Comment by sagatowski** [comment]
TcUnit.org reference moved, and didn't think of moving these files over. Need to find a backup of them and upload them somewhere else.

**Comment by sagatowski** [comment]
Issue solved. Removed broken link to example for running tests over multiple cycles and replaced with an example in the documentation/FAQ instead.
