### ISSUE TITLE
An empty test suite causes the test report to never show

### ISSUE THREAD

**Issue by claytonketner** [tcunit/TcUnit#30]
If you have a test suite with nothing in the body of the FB (i.e. if no test methods are called, and thus `TEST()` and `TEST_FINISHED()` are never called in the test suite), the final test report never gets logged. This is likely due to the runner thinking it is still running tests.

I thought this might be a quick fix by modifying `FB_TestSuite`'s `AllTestsFinished` method and making it print a warning and return true if `NumberOfTests` is 0, but it seems like on the first cycle, `NumberOfTests` is always zero. That might be easily fixable by changing the order of execution of some things, but I haven't had a chance to take a deeper look yet.

**Comment by sagatowski** [comment]
Sorry I'm not 100% sure I fully understand. You mean empty test-suite in that it has no test cases and no asserts? If so, what would be the best suggestion? Maybe checking that if we execute a test-suite, and we detect a new test-suite without running any tests, we should output an error message? Thanks for this find!

**Comment by Aliazzzz** [comment]
Hi,

I also do not follow this.

Maybe it would be a good idea to upload a small code example which yields this bug.
Otherwise we keep guessing.

From there we can assess whether this issue is a bug or a user problem or not.

Aliazzz
________________________________

**Comment by claytonketner** [comment]
Yeah apologies for the lack of writeup. I updated the OP with more detail.

**Comment by sagatowski** [comment]
Thanks for the clarification. I'll look at the issue.

**Comment by slacAWallace** [comment]
Experiencing something similar. Bumped to 0.9, refactored and the test summary stopped displaying. I have two empty test suites.

**Comment by sagatowski** [comment]
> Experiencing something similar. Bumped to 0.9, refactored and the test summary stopped displaying. I have two empty test suites.
> 
> edit
> Yeap, definitely the same thing. I made sure all tests were FINISHED and the summary reappeared.

Thanks Alex. I'll try to look into this as soon as possible (and for sure before the 1.0 release).

**Comment by sagatowski** [comment]
Solved in commit 094faf7f. If no test-cases are declared in a test-suite, this test-suite is simply ignored. The way this is detected is that if we are on the second cycle (or later) and no tests have been run for that test-suite in the first cycle, we consider that test-suite as incomplete and simply ignore it (AllTestsFinished = True).

If the user has tests declared (like TEST('ThisIsATest')) but forgets to add TEST_FINISHED() there is nothing the framework can do, because we simply don't know for how long a user wants to run a certain tests before considering it TEST_FINISHED().

**Comment by sagatowski** [comment]
> Experiencing something similar. Bumped to 0.9, refactored and the test summary stopped displaying. I have two empty test suites.
> 
> edit
> Yeap, definitely the same thing. I made sure all tests were FINISHED and the summary reappeared.

Alex, you're welcome to clone the latest version (only source, no release yet) and see if it works out for you.

**Comment by slacAWallace** [comment]
OK I will try it. BTW, 0.9.0 is awesome! Multi-cycle FB unit testing is really helping me out!

**Comment by Aliazzzz** [comment]
Hi,

I have also made a very handy multi cycle testframework in CODESYS for CfUnit, should I redo it for TwinCAT? May it helps you even better? Let me know.
