### ISSUE TITLE
Change methods GetAmount... to GetNumber...

### ISSUE THREAD

**Issue by Roald87** [tcunit/TcUnit#39]
Before you freeze the API method names it might be good to change the method names which start with `GetAmount...` to `GetNumber...`. From the [Cambridge dictionary](https://dictionary.cambridge.org/grammar/british-grammar/amount-of-number-of-or-quantity-of):

> We use amount of with uncountable nouns. Number of is used with countable nouns:

So `GetAmountOfFailedTests` then becomes `GetNumberOfFailedTests`.

**Comment by sagatowski** [comment]
Excellent suggestion, thank you for this great feedback! Will be implemented in next release.

**Comment by sagatowski** [comment]
Solved in commit 6387ca3.
