### ISSUE TITLE
TEST_FINISHED_NAMED should warn if name doesn't exist

### ISSUE THREAD

**Issue by sagatowski** [tcunit/TcUnit#42]
Related to issue #38.
If TEST_FINISHED_NAMED is called with a name for a test that doesn't exist, the user should be warned (by standard ADSLOGSTR).

**Comment by slacAWallace** [comment]
Started on this tonight. Will test it tomorrow and make pr.

**Comment by sagatowski** [comment]
Great Alex, looking forward to your PR!

**Comment by slacAWallace** [comment]
@sagatowski What do you think about keeping the bleeding edge of master set to 0.0.0.0 and unreleased and only setting version numbers on tags? I find I keep changing the project version to avoid interfering with my real install of TcUnit. Also with 4024, the released checkbox prevents changes to the code.

**Comment by Aliazzzz** [comment]
Hi,

Though the idea sounds good, I’d consider not to do that.
Especially in a big project it is an unwise decision to set the version to a lower or even unused versionnumber then the currently released version as you easily lose track of the version and changes.
We should keep the unreleased version always higher than the released version.

I have got the following empirical library development guidelines on versioning of CODESYS and TwinCAT libraries for you to get an idea on how to use it;
https://forge.codesys.com/forge/community/Developer%20Community%20Documentation/#versioning-of-own-items

With kind regards,


Aliazzz

**Comment by sagatowski** [comment]
I'd have to agree on the middle-road between these two. I'll keep the version number to a later one than the latest released/tag, but only set the "released"-flag once it's time for a tag/formal release.

**Comment by slacAWallace** [comment]
I wish the git describe output could be used in lieu of a proper tc version, until the released button is checked. :(

**Comment by sagatowski** [comment]
Alex, my plan is to release TcUnit version 1.0 this weekend. Do you think you'll have time to finish this + add tests to TcUnit-Verifier prior to that?

Cheers
