### ISSUE TITLE
FB_Stringbuffer; add a .Clear() method

### ISSUE THREAD

**Issue by Aliazzzz** [tcunit/TcUnit#49]
Add a method that clears the buffer and sets the current bufferlength to zero (0)

**Comment by Aliazzzz** [comment]
method written

**Comment by Aliazzzz** [comment]
pushing these changes later today

**Comment by sagatowski** [comment]
You don't want to keep the issue open until all is commited & pushed?

**Comment by Aliazzzz** [comment]
Should I push them?
I rather release it in 1.0.xx.yy with a "working" Xml generated

**Comment by Aliazzzz** [comment]
Clear method is ready. 
Now working a new release of the filewriter
