### ISSUE TITLE
FB_Stringbuffer; add .prepend() method

### ISSUE THREAD

**Issue by Aliazzzz** [tcunit/TcUnit#50]
Add a method that prepends a string to current buffer.
This method should be called via method .AddDocumentHeader( ... )

**Comment by Aliazzzz** [comment]
method ready

**Comment by Aliazzzz** [comment]
pushing these changes later today

**Comment by sagatowski** [comment]
You don't want to keep the issue open until all is commited & pushed?

**Comment by sagatowski** [comment]
How is it progressing with the code?

**Comment by Aliazzzz** [comment]
Progress has slown down due to time constraints.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Aliazzzz** [comment]
Prepend() method is ready. 
Now working a new release of the filewriter
