### ISSUE TITLE
TEST_FINISHED() seems to not pass through the complete TcUnit stack

### ISSUE THREAD

**Issue by arpitpatel901** [tcunit/TcUnit#55]
In the case when a TEST needs to run multiple scans before it is finished, the TEST_FINISHED() api does not seem to completely exit out of the TcUnit stack frame(has no output in the Output/Error List) window.

[Test code link](https://drive.google.com/file/d/1RTmpwNBIGJwQVclgkq45mXMOf0wmjIul/view?usp=sharing)

**Comment by sagatowski** [comment]
Thanks for creating this issue. I will investigate this.

**Comment by sagatowski** [comment]
I've looked at the code, and for some reason you are calling TEST_FINISHED twice for each test. For each TEST(''), you are only supposed to call TEST_FINISHED() once.
I removed the two TEST_FINISHED() in the body of FB_AirCylinder_Test, and then the test suite passed through (although with one failed and one successful test).

**Comment by sagatowski** [comment]
@arpitpatel901 , could you confirm this indeed solved your issue?

**Comment by sagatowski** [comment]
@arpitpatel901, Closing this issue. If you can re-create the issue, please open it again.
