### ISSUE TITLE
The call_after_init attribute is unnecessary in test suites.

### ISSUE THREAD

**Issue by KubaO** [tcunit/TcUnit#59]
The `{attribute 'call_after_init'}` is not necessary for the test suites in the current implementation of TcUnit. Everything works without it - it was only necessary in the original implementation. The `FB_TestSuite` function block has no methods that are `call_after_init`, and it extends no function blocks, thus it's just an unnecessary leftover.

The use of this attribute for test suites should be removed from the examples, documentation, and the verifier tests.

**Comment by sagatowski** [comment]
Good catch!
Fixed both example projects, verifier tests, and all documentation on the TcUnit-website.
Thanksl
