### ISSUE TITLE
TcUnit FileExport

### ISSUE THREAD

**Issue by danydimy** [tcunit/TcUnit#67]
Hi Jacob,
is it possible to have a "File Export" feature inside TcUnit?
It should be useful to create a own log of the tests already done.
I noticed the FileControl FB inside library, and it works (tried with general purpose code).
Thanks in advance.

Regards,

          Daniele

**Comment by Aliazzzz** [comment]
See Export results in Xunit XML format #11

**Comment by sagatowski** [comment]
Implemented in 4961aa9e036c6eae6a4a46422a37bd35f461c35c.
