### ISSUE TITLE
Releasing openxml and .library sourcecode for future master release

### ISSUE THREAD

**Issue by Aliazzzz** [tcunit/TcUnit#69]
Dear TcUnit,

I would like to request that the code from the nextmaster will be made available as;

.Library,
OpenXml export,
.compiled-library,
And offcourse 
TcUnit sourcecode from the above artefacts are derived.

Reason is that I can use the .library (NOT to be confused with the .compiled-library) and the open xml exports to update CfUnit.

**Comment by Aliazzzz** [comment]
Offcourse I mean all future master releases...

**Comment by sagatowski** [comment]
For the very specific case of CfUnit using this, I think it makes more sense for the developers to simply download the code in a release (which is also provided for a release), and do the exports.

I think > 99% of the users of TcUnit only want to use the compiled-library (+ the documentation obviously). I'm worried that new people to the framework might get nervous when there are several files to download, while they only need one single of them.

**Comment by Aliazzzz** [comment]
No problem, You are probably right that the majority doesn't need it. Anyway thanks for the consideration.
