### ISSUE TITLE
Add tests for WRITE_PROTECTED_ functions

### ISSUE THREAD

**Issue by sagatowski** [tcunit/TcUnit#83]
Add tests for the WRITE_PROTECTED_ functions in the .NET-verifier. There are already tests in the TwinCAT verifier, we just need to make sure these output (or rather, don't output) the correct values.

**Comment by Aliazzzz** [comment]
The test FB for these tests is not fashioned in a real world application type of way. I will do a suggestion for an improvement on this test.

**Comment by sagatowski** [comment]
Thanks for implementing this. Please add the class FB_WriteProtectedFunctions in the C#/.NET verifier and update the Program-class.

**Comment by sagatowski** [comment]
Have you made any progress on this? Otherwise I'll implement it.

**Comment by sagatowski** [comment]
Sorry, didn't have the patience to wait. Fixed :-)
Solved in commit c50dcd8.
