### ISSUE TITLE
Calculation of amount of test cases is not correct

### ISSUE THREAD

**Issue by sagatowski** [tcunit/TcUnit#84]
Note, the bug below is only applicable in the current main-branch trunk (not any release).

In the new FB_TestResults, it seems that the NumberOfTestCases is not calculated correctly.

For example, in the advanced example project, the number of tests should be 17, but only 15 are presented. It seems the last test suite is not included.

Suggested solution:
Revert back to the old solution without FB_TestResults that was working before the introduction of this new class, or try to find the problem.

**Comment by Aliazzzz** [comment]
I suspect the problem lies in FB_TcUnitRunner.RunTestSuiteTests() method.
Hope this helps..

**Comment by sagatowski** [comment]
@Aliazzzz much appreciated If you could investigate the issue

**Comment by Aliazzzz** [comment]
Sorry, am busy with loads of other stuff for TcUnit at this moment ...


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sagatowski** [comment]
Solved in 135307a
