### ISSUE TITLE
Sequential test suits

### ISSUE THREAD

**Issue by PaulNBarron** [tcunit/TcUnit#97]
Hi,
Is it possible to run the test suits sequentially? For example if I have TestSuite1_FB and TestSuite2_FB is it possible to wait until TestSuite1_FB has finished executing before starting TestSuite2_FB?
Thanks

**Comment by sagatowski** [comment]
Hi!

No. Tests should not be dependent on each other. See #8 here:
https://medium.com/better-programming/13-tips-for-writing-useful-unit-tests-ca20706b5368

**Comment by sagatowski** [comment]
Also:
https://github.com/tcunit/TcUnit/issues/95
